/*
 * @Author: 矢车
 * @Date: 2020-11-21 14:39:55
 * @LastEditors: 矢车
 * @LastEditTime: 2020-11-21 16:43:56
 * @Description:
 */
/**
 * 工作台 actions
 * @author  Jerry <superzcj_001@163.com>
 * @since   2020-11-20 19:25:52
 */

/**
 * 设置审批单详情
 * @author  Jerry <superzcj_001@163.com>
 * @since   2020-11-21 09:49:01
 */
export const SET_APPROVAL = 'SET_APPROVAL';

/**
 * 清楚审批单详情
 * @author  Jerry <superzcj_001@163.com>
 * @since   2020-11-21 23:51:21
 */
export const CLEAR_APPROVAL = 'CLEAR_APPROVAL';

export const SET_LOAN_FORM_VISIBLE = 'SET_LOAN_FORM_VISIBLE';
export const SET_LOAN_DETAIL_VISIBLE = 'SET_LOAN_DETAIL_VISIBLE';
export const SET_REFUND_FORM_VISIBLE = 'SET_REFUND_FORM_VISIBLE';
export const SET_REFUND_DETAIL_VISIBLE = 'SET_REFUND_DETAIL_VISIBLE';
export const SET_ADVANCE_FORM_DIALOG_VISIBLE = 'SET_ADVANCE_FORM_DIALOG_VISIBLE';
export const SET_ADVANCE_FORM_VISIBLE = 'SET_ADVANCE_FORM_VISIBLE';
export const SET_ADVANCE_DETAIL_VISIBLE = 'SET_ADVANCE_DETAIL_VISIBLE';
export const SET_INVOICING_FORM_VISIBLE = 'SET_INVOICING_FORM_VISIBLE';
export const SET_INVOICING_DETAIL_VISIBLE = 'SET_INVOICING_DETAIL_VISIBLE';
export const SET_CUSTOMER_DETAIL_VISIBLE = 'SET_CUSTOMER_DETAIL_VISIBLE';
export const SET_SUPPLIER_DETAIL_VISIBLE = 'SET_SUPPLIER_DETAIL_VISIBLE';
export const SET_RED_DETAIL_VISIBLE = 'SET_RED_DETAIL_VISIBLE';
export const SET_VOID_DETAIL_VISIBLE = 'SET_VOID_DETAIL_VISIBLE';
export const SET_USE_SEAL_DETAIL_VISIBLE = 'SET_USE_SEAL_DETAIL_VISIBLE';
export const SET_PROJECT_APPROVAL_VISIBLE = 'SET_PROJECT_APPROVAL_VISIBLE';
export const SET_PROJECT_END_VISIBLE = 'SET_PROJECT_END_VISIBLE';
export const SET_ASSET_SCRAPPED_VISIBLE = 'SET_ASSET_SCRAPPED_VISIBLE';
