/**
 * 形象设计相关
 */

// 预约状态
export enum EAPPOINTMENT_STATUS {
  PENDING_ORDER = 1,
  TOBE_COMPLETED,
  COMMENT,
  PENDING_UPLOAD,
  INVOICED,
  WITHDRAWN,
  CHARGED_BACK,
}

export const EAPPOINTMENT_STATUS_MAP = new Map([
  [EAPPOINTMENT_STATUS.PENDING_ORDER, '待接单'],
  [EAPPOINTMENT_STATUS.TOBE_COMPLETED, '待完成'],
  [EAPPOINTMENT_STATUS.COMMENT, '待评价'],
  [EAPPOINTMENT_STATUS.PENDING_UPLOAD, '待上传'],
  [EAPPOINTMENT_STATUS.INVOICED, '已结单'],
  [EAPPOINTMENT_STATUS.WITHDRAWN, '已撤回'],
  [EAPPOINTMENT_STATUS.CHARGED_BACK, '已退单'],
]);

export const EAPPOINTMENT_STATUS_OPTIONS: TG.OptionType<EAPPOINTMENT_STATUS>[] = [
  { label: '待接单', value: EAPPOINTMENT_STATUS.PENDING_ORDER },
  { label: '待完成', value: EAPPOINTMENT_STATUS.TOBE_COMPLETED },
  { label: '待评价', value: EAPPOINTMENT_STATUS.COMMENT },
  { label: '待上传', value: EAPPOINTMENT_STATUS.PENDING_UPLOAD },
  { label: '已结单', value: EAPPOINTMENT_STATUS.INVOICED },
  { label: '已撤回', value: EAPPOINTMENT_STATUS.WITHDRAWN },
  { label: '已退单', value: EAPPOINTMENT_STATUS.CHARGED_BACK },
];
