/**
 * 绩效管理
 * @author  Jerry <superzcj_001@163.com>
 * @since   2020-12-09 11:36:28
 */
import { RouteConfig } from 'vue-router';
import { RouterNamePerformance } from '@/const/router';
import RouterViewEmptyPage from '@/layouts/empty.vue';
import { RIGHT_CODE } from '@/const/rightCode';
import { routeParams2Props } from '@/router/func';

export const performance: RouteConfig[] = [
  {
    path: '/performance',
    component: RouterViewEmptyPage,
    props: {
      version: 1,
    },
    meta: {
      name: '绩效管理',
      icon: 'ico-menu-jixiaoguanli',
      isKeepLive: true,
      noauth: true,
      right: [
        RIGHT_CODE.performance_management,
        RIGHT_CODE.indicators_library_view,
        RIGHT_CODE.evaluation_group_view,
        RIGHT_CODE.assessment_management_view,
        RIGHT_CODE.debriefing_manage_view,
      ],
    },
    children: [
      {
        path: '/performance/indicatorLibrary',
        name: RouterNamePerformance.indicatorLibrary.list,
        component: () => import('../modules/performance/indicatorLibrary'),
        meta: {
          name: '指标库',
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          parentPath: '/performance',
          right: [RIGHT_CODE.indicators_library_view],
        },
      },
      {
        path: '/performance/indicatorLibrary/create/:id?',
        name: RouterNamePerformance.indicatorLibrary.create,
        component: () => import('../modules/performance/indicatorLibrary/create/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '创建指标',
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          hidden: true,
          activePath: '/performance/indicatorLibrary',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/assessment',
        name: RouterNamePerformance.assessment.list,
        component: () => import('../modules/performance/assessment'),
        props: routeParams2Props,
        meta: {
          name: '考评组',
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          activePath: '/performance/assessment',
          parentPath: '/performance',
          right: [RIGHT_CODE.evaluation_group_view],
        },
      },
      {
        path: '/performance/assessment/create',
        component: () => import('../modules/performance/assessment/create/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '创建考评组',
          hidden: true,
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          activePath: '/performance/assessment',
          parentPath: '/performance',
          right: [],
        },
        children: [
          {
            path: '/performance/assessment/create/base',
            name: RouterNamePerformance.assessment.create.base,
            component: () => import('../modules/performance/assessment/create/base/index.vue'),
            props: routeParams2Props,
            meta: {
              name: '创建考评组',
              hidden: true,
              hirouteParams2Propsen: false,
              class: 'cls-star-info',
              isKeepLive: true,
              activePath: '/performance/assessment',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/assessment/create/indicators',
            name: RouterNamePerformance.assessment.create.indicators,
            component: () =>
              import('../modules/performance/assessment/create/indicators/index.vue'),
            props: routeParams2Props,
            meta: {
              name: '创建考评组',
              hidden: true,
              hirouteParams2Propsen: false,
              class: 'cls-star-info',
              isKeepLive: true,
              activePath: '/performance/assessment',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/assessment/create/process',
            name: RouterNamePerformance.assessment.create.process,
            component: () => import('../modules/performance/assessment/create/process/index.vue'),
            props: routeParams2Props,
            meta: {
              name: '创建考评组',
              hidden: true,
              hirouteParams2Propsen: false,
              class: 'cls-star-info',
              isKeepLive: true,
              activePath: '/performance/assessment',
              parentPath: '/performance',
              right: [],
            },
          },
        ],
      },
      {
        path: '/performance/assessment/preview',
        name: RouterNamePerformance.assessment.preview,
        component: () => import('../modules/performance/assessment/preview/index.vue'),
        props: routeParams2Props,
        meta: {
          hidden: true,
          name: '创建考评组',
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          activePath: '/performance/assessment',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/assessment/manage',
        name: RouterNamePerformance.assessment.manage.list,
        component: () => import('../modules/performance/assessment/manage/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '考核管理',
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          activePath: '/performance/assessment/manage',
          parentPath: '/performance',
          right: [RIGHT_CODE.assessment_management_view],
        },
      },
      {
        path: '/performance/assessment/manage/:id',
        name: RouterNamePerformance.assessment.manage.detailList,
        component: () => import('../modules/performance/assessment/manage/$id/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '考核详情',
          hidden: true,
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          isKeepLive: true,
          activePath: '/performance/assessment/manage',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/assessment/manage/:id/:userid',
        name: RouterNamePerformance.assessment.manage.detailDetail,
        component: () => import('../modules/performance/assessment/manage/$id/$userid/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '员工绩效详情',
          hidden: true,
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          activePath: '/performance/assessment/manage',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/report/detailDetail/:id/:userid',
        name: RouterNamePerformance.report.detailDetail,
        component: () => import('../modules/performance/assessment/manage/$id/$userid/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '员工绩效详情',
          hidden: true,
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          activePath: '/performance/report/record',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/report/result_analysis_detail/:id/:userid',
        name: RouterNamePerformance.report.result_analysis_detail,
        component: () => import('../modules/performance/assessment/manage/$id/$userid/index.vue'),
        props: routeParams2Props,
        meta: {
          name: '员工绩效详情',
          hidden: true,
          hirouteParams2Propsen: false,
          class: 'cls-star-info',
          activePath: '/performance/report/result_analysis',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/my',
        component: () => import('../modules/performance/my/index.vue'),
        props: routeParams2Props,
        redirect: '/performance/my/own',
        meta: {
          name: '我的绩效',
          class: 'cls-star-info',
          noauth: true,
          right: [],
          isKeepLive: true,
        },
        children: [
          {
            path: '/performance/my/own',
            name: RouterNamePerformance.my.own.list,
            component: () => import('../modules/performance/my/own/index.vue'),
            meta: {
              name: '我的绩效',
              hidden: false,
              class: 'cls-star-info',
              activePath: '/performance/my',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/my/related',
            name: RouterNamePerformance.my.related.list,
            component: () => import('../modules/performance/my/related/index.vue'),
            meta: {
              name: '我的绩效',
              hidden: false,
              class: 'cls-star-info',
              activePath: '/performance/my',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/my/underling',
            name: RouterNamePerformance.my.underling.list,
            component: () => import('../modules/performance/my/underling/index.vue'),
            meta: {
              name: '我的绩效',
              hidden: false,
              class: 'cls-star-info',
              activePath: '/performance/my',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/my/debriefing/minie',
            name: RouterNamePerformance.debriefing.mine,
            component: () => import('../modules/performance/debriefing/mine/index.vue'),
            meta: {
              name: '我的绩效',
              hidden: false,
              class: 'cls-star-info',
              activePath: '/performance/my',
              parentPath: '/performance',
              right: [],
            },
          },
          {
            path: '/performance/my/debriefing/underling',
            name: RouterNamePerformance.debriefing.underling,
            component: () => import('../modules/performance/debriefing/underling/index.vue'),
            meta: {
              name: '我的绩效',
              hidden: false,
              class: 'cls-star-info',
              activePath: '/performance/my',
              parentPath: '/performance',
              right: [],
            },
          },
        ],
      },
      {
        path: '/performance/my/own/:id',
        name: RouterNamePerformance.my.own.detail,
        component: () => import('../modules/performance/my/own/$id/index.vue'),
        meta: {
          name: '我的绩效',
          hidden: true,
          class: 'cls-star-info',
          activePath: '/performance/my',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/my/related/:id',
        name: RouterNamePerformance.my.related.detail,
        component: () => import('../modules/performance/my/own/$id/index.vue'),
        meta: {
          name: '我的绩效',
          hidden: true,
          class: 'cls-star-info',
          activePath: '/performance/my',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/my/underling/:id',
        name: RouterNamePerformance.my.underling.detail,
        component: () => import('../modules/performance/my/own/$id/index.vue'),
        meta: {
          name: '我的绩效',
          hidden: true,
          class: 'cls-star-info',
          activePath: '/performance/my',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/debriefing/manage',
        name: RouterNamePerformance.debriefing.manage,
        component: () => import('../modules/performance/debriefing/manage/index.vue'),
        meta: {
          name: '述职管理',
          class: 'cls-star-info',
          activePath: '/performance/debriefing/manage',
          parentPath: '/performance',
          right: [RIGHT_CODE.debriefing_manage_view],
        },
      },
      {
        path: '/performance/debriefing/manage/list/:id',
        name: RouterNamePerformance.debriefing.list,
        component: () => import('../modules/performance/debriefing/manage/list.vue'),
        meta: {
          name: '述职清单',
          class: 'cls-star-info',
          hidden: true,
          activePath: '/performance/debriefing/manage',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/report/result_analysis',
        name: RouterNamePerformance.report.result_analysis,
        component: () => import('../modules/performance/report/result_analysis/index.vue'),
        meta: {
          name: '考核结果分析',
          class: 'cls-star-info',
          activePath: '/performance/report/result_analysis',
          parentPath: '/performance',
          right: [RIGHT_CODE.performance_report_analysis_view],
        },
      },
      {
        path: '/performance/report/record',
        name: RouterNamePerformance.report.record,
        component: () => import('../modules/performance/report/record/index.vue'),
        meta: {
          name: '员工绩效档案',
          class: 'cls-star-info',
          activePath: '/performance/report/record',
          parentPath: '/performance',
          right: [RIGHT_CODE.performance_report_performance_view],
        },
      },
      {
        path: '/performance/report/record/:id',
        name: RouterNamePerformance.report.detail,
        component: () => import('../modules/performance/report/record/$id/index.vue'),
        meta: {
          name: '员工绩效考核详情',
          class: 'cls-star-info',
          hidden: true,
          activePath: '/performance/report/record',
          parentPath: '/performance',
          right: [],
        },
      },
      {
        path: '/performance/processMonitoring',
        name: RouterNamePerformance.processMonitoring,
        component: () => import('../modules/performance/processMonitoring/index.vue'),
        meta: {
          name: '实施流程监控',
          class: 'cls-star-info',
          activePath: '/performance/processMonitoring',
          parentPath: '/performance',
          right: [RIGHT_CODE.implement_monitor_process],
        },
      },
    ],
  },
  // {
  //   path: '/performance/report',
  //   component: RouterViewEmptyPage,
  //   meta: {
  //     name: '绩效报表',
  //     icon: 'ico-icon_cebianlan_jixiaobaobiao',
  //     right: [
  //       RIGHT_CODE.performance_report,
  //       RIGHT_CODE.performance_report_analysis_view,
  //       RIGHT_CODE.performance_report_performance_view,
  //     ],
  //   },
  //   children: [
  // {
  //   path: '/performance/report/result_analysis',
  //   name: RouterNamePerformance.report.result_analysis,
  //   component: () => import('../modules/performance/report/result_analysis/index.vue'),
  //   meta: {
  //     name: '考核结果分析',
  //     class: 'cls-star-info',
  //     activePath: '/performance/report/result_analysis',
  //     parentPath: '/performance/report',
  //     right: [RIGHT_CODE.performance_report_analysis_view],
  //   },
  // },
  // {
  //   path: '/performance/report/record',
  //   name: RouterNamePerformance.report.record,
  //   component: () => import('../modules/performance/report/record/index.vue'),
  //   meta: {
  //     name: '员工绩效档案',
  //     class: 'cls-star-info',
  //     activePath: '/performance/report/record',
  //     parentPath: '/performance/report',
  //     right: [RIGHT_CODE.performance_report_performance_view],
  //   },
  // },
  // {
  //   path: '/performance/report/record/:id',
  //   name: RouterNamePerformance.report.detail,
  //   component: () => import('../modules/performance/report/record/$id/index.vue'),
  //   meta: {
  //     name: '员工绩效考核详情',
  //     class: 'cls-star-info',
  //     hidden: true,
  //     activePath: '/performance/report/record',
  //     parentPath: '/performance/report',
  //     right: [],
  //   },
  // },
  //   ],
  // },
];
