function mm(){
	mv $1.js $1.ts
}

mm api/auth
mm api/brand
mm api/candidate
mm api/cooperative
mm api/customer
mm api/display
mm api/medium
mm api/star
mm api/stat
mm api/upload
mm api/user
mm api/workbench
mm assets/iconfont/iconfont
mm components/index
mm components/tipDialog/extend/index
mm const/cooperative
mm const/getStar
mm const/kolConst
mm const/optionChart
mm const/options
mm const/roleCode
mm router/index
mm store/index
mm store/modules/cooperative/actions
mm store/modules/cooperative/actiontypes
mm store/modules/cooperative/chatrecord/actions
mm store/modules/cooperative/chatrecord/actiontypes
mm store/modules/cooperative/chatrecord/mutations
mm store/modules/cooperative/cooperation/actions
mm store/modules/cooperative/cooperation/actiontypes
mm store/modules/cooperative/cooperation/mutations
mm store/modules/cooperative/execute/actions
mm store/modules/cooperative/execute/actiontypes
mm store/modules/cooperative/execute/mutations
mm store/modules/cooperative/getters
mm store/modules/cooperative/index
mm store/modules/cooperative/mutations
mm store/modules/cooperative/state
mm store/modules/customer/getters
mm store/modules/customer/index
mm store/modules/customer/mutations
mm store/modules/customer/state
mm store/modules/requirement/getters
mm store/modules/requirement/index
mm store/modules/requirement/mutations
mm store/modules/requirement/state
mm store/modules/user/getters
mm store/modules/user/index
mm store/modules/user/mutations
mm store/modules/user/state
mm utils/city
mm utils/config
mm utils/filter
mm utils/format
mm utils/init
mm utils/request
mm utils/token
mm utils/tools
mm utils/variable
mm views/customer/cooperative/mixin/CooperativeStore
mm views/customer/cooperative/mixin/CurrentUserPower
mm views/medium/components/platform/index
